# -*- coding: utf-8 -*-
"""qwen-mech-interp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14j0v_AyhRh0AyhdnV6dTAqWBm-1J8pJk
"""

# Let's install the tools we'll need for our project
!pip install "transformers" "datasets" "accelerate" "peft" "bitsandbytes" "transformer_lens" "trl"

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

# The specific Qwen model we'll use
model_id = "Qwen/Qwen1.5-0.5B-Chat"

# This is our QLoRA configuration.
# It tells the transformer to load the model in 4-bit precision, which saves a ton of memory.
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

# Load the model from Hugging Face with our special config
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto" # This automatically puts the model on the GPU if it's available
)

# Load the tokenizer that matches the model
tokenizer = AutoTokenizer.from_pretrained(model_id)

# A quick check to make sure everything is ready
print("✅ Model and tokenizer loaded successfully!")


# ================================
# == OPTIMIZATION SUMMARY ==
# No changes were made to the code as it already uses the most important memory-saving technique:
#
# 1.  `load_in_4bit=True`: This loads the model weights using only 4 bits per parameter instead of the usual 32 or 16.
#     This reduces the model's memory footprint by up to 8x.
# 2.  `bnb_4bit_compute_dtype=torch.bfloat16`: While the model is stored in 4-bit, computations (like matrix multiplications)
#     are performed in 16-bit for accuracy and stability. This is a good trade-off between performance and memory.
# 3.  `device_map="auto"`: This intelligently places the model parts on the available hardware (GPU/CPU), which is essential for making the most of a free-tier GPU.
# ================================

from transformer_lens import HookedTransformer
import gc

print("\n" + "="*50)
print("🚀 Running the 'BEFORE' benchmark on the base model ...")
print("="*50)

# We load the HookedTransformer, but we'll delete it right after use
# to free up memory for fine-tuning.
# NOTE: This still temporarily loads a full-precision copy of the model.
# On extremely constrained systems, you might need to skip this analysis step entirely.
hooked_model = HookedTransformer.from_pretrained(model_id)
hooked_model.to("cuda" if torch.cuda.is_available() else "cpu")
hooked_model.eval()

# Our test prompt
test_prompt="""
Write a Python program that shows 20 balls bouncing inside a spinning hexagon:
- All balls have the same radius.
- All balls have a number on it from 1 to 20.
- All balls drop from the heptagon center when starting.
- Colors are: #f8b862, #f6ad49, #f39800, #f08300, #ec6d51, #ee7948, #ed6d3d, #ec6800, #ec6800, #ee7800, #eb6238, #ea5506, #ea5506, #eb6101, #e49e61, #e45e32, #e17b34, #dd7a56, #db8449, #d66a35
- The balls should be affected by gravity and friction, and they must bounce off the rotating walls realistically. There should also be collisions between balls.
- The material of all the balls determines that their impact bounce height will not exceed the radius of the heptagon, but higher than ball radius.
- All balls rotate with friction, the numbers on the ball can be used to indicate the spin of the ball.
- The heptagon is spinning around its center, and the speed of spinning is 360 degrees per 5 seconds.
- The heptagon size should be large enough to contain all the balls.
- Do not use the pygame library; implement collision detection algorithms and collision response etc. by yourself. The following Python libraries are allowed: tkinter, math, numpy, dataclasses, typing, sys.
- All codes should be put in a single Python file.
"""
chat_prompt = tokenizer.apply_chat_template(
    [
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": test_prompt},
    ],
    tokenize=False,
    add_generation_prompt=True,
)

# --- STEP 1: Generate Text using the standard Hugging Face method ---
# We use our memory-efficient 4-bit model for this generation
inputs = tokenizer(chat_prompt, return_tensors="pt").to(model.device)
generated_ids = model.generate(
    inputs.input_ids,
    do_sample=True,          # Enable sampling for top_p to work
    top_p=0.9,
    temperature=0.7,
    max_new_tokens=1000,     # Increased to allow full code generation
    repetition_penalty=1.1
)
base_model_output_text = tokenizer.decode(generated_ids[0])

print("\n--- Base Model Output ---\n")
print(base_model_output_text)
print("\n-------------------------\n")


# --- STEP 2: Analyze by running the full text through run_with_cache ---
print("Analyzing the generation process...")
with torch.no_grad(): # Ensure no gradients are computed
    _, base_model_cache = hooked_model.run_with_cache(base_model_output_text)

print("✅ 'BEFORE' benchmark complete.")

# --- OPTIMIZATION: Explicitly delete the large objects and clear CUDA cache ---
print("Cleaning up memory before fine-tuning...")
del hooked_model
del base_model_cache
gc.collect()
torch.cuda.empty_cache()
print("✅ Memory cleaned.")


# ================================
# == OPTIMIZATION SUMMARY ==
# 1.  `Sequential Operation`: The original code kept two models in memory simultaneously. This version runs the
#     `HookedTransformer` analysis and then immediately deletes the objects.
# 2.  `del hooked_model, del base_model_cache`: We explicitly tell Python to remove our references to these large objects.
#     The `hooked_model` is a full-precision model, and `base_model_cache` contains all the activations, so they are both very large.
# 3.  `gc.collect()`: This forces Python's garbage collector to run, reclaiming memory from the deleted objects.
# 4.  `torch.cuda.empty_cache()`: This releases all unused cached memory on the GPU that PyTorch was holding onto.
#     This sequence ensures that the maximum amount of VRAM is available for the most demanding step: fine-tuning.
# ================================

from datasets import load_dataset
import sys

print("🚀 Starting dataset preparation...")
dataset = load_dataset("deepmind/code_contests", split="train")
dataset = dataset.shuffle(seed=42).select(range(5000))

# Inspecting language IDs in a few examples to identify Python
all_langs = []
for i in range(20):
    langs = dataset[i]["solutions"]["language"]
    all_langs.extend(langs)
unique_langs = sorted(set(all_langs))
print("Unique language IDs in sample:", unique_langs)

language_examples = {}
for i in range(20):
    sol = dataset[i]["solutions"]
    for lang, code in zip(sol["language"], sol["solution"]):
        if lang not in language_examples:
            language_examples[lang] = []
        if len(language_examples[lang]) < 3:
            language_examples[lang].append(code)
for lang, codes in language_examples.items():
    print(f"Lang {lang} example: {repr(codes[0][:80])} ...")

# Manually set this after inspecting output above, e.g., 1 for Python
PYTHON_LANG_ID = 1


def format_chat_template(examples):
    texts = []
    for i in range(len(examples["description"])):
        sol = examples["solutions"][i]
        langs = sol["language"]
        codes = sol["solution"]
        # Extract Python solutions based on language ID
        py_solutions = [code for lang, code in zip(langs, codes) if lang == PYTHON_LANG_ID]
        if py_solutions:
            formatted_text = tokenizer.apply_chat_template(
                [
                    {"role": "system", "content": "You are a helpful assistant that solves coding problems."},
                    {"role": "user", "content": examples["description"][i]},
                    {"role": "assistant", "content": py_solutions[0]},
                ],
                tokenize=False,
                add_generation_prompt=False,
            )
            texts.append(formatted_text + tokenizer.eos_token)
        else:
            texts.append(None)
    return {"text": texts}


print("\nFormatting and filtering examples...")
original_columns = dataset.column_names
dataset = dataset.map(format_chat_template, batched=True, remove_columns=original_columns)
dataset = dataset.filter(lambda example: example["text"] is not None)

# Limit dataset size for efficient training
DESIRED_SIZE = 1000
if len(dataset) > DESIRED_SIZE:
    dataset = dataset.select(range(DESIRED_SIZE))

if len(dataset) == 0:
    print("❌ No valid Python solutions found.")
    sys.exit()

print(f"✅ Dataset prepared with {len(dataset)} examples.")

from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from transformers import TrainerCallback
from transformers.utils import logging


# Enable verbose logging including progress bar and detailed info
logging.set_verbosity_info()


class VerboseCallback(TrainerCallback):
    def on_step_end(self, args, state, control, **kwargs):
        loss_val = None
        if state.log_history and 'loss' in state.log_history[-1]:
            loss_val = state.log_history[-1]['loss']
        print(f"[Step {state.global_step}/{state.max_steps}] Loss: {loss_val}")


# LoRA parameter-efficient fine-tuning config
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

# Supervised Fine-Tuning config with frequent logging
sft_config = SFTConfig(
    dataset_text_field="text",
    output_dir="./qwen-sft-finetuned",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_strategy="steps",
    logging_steps=1,        # Log every training step for maximum visibility
    optim="paged_adamw_8bit",
    save_strategy="epoch",
    fp16=True,
    report_to=[],           # Disable wandb logging prompts
)

# Instantiate trainer with verbose callback
trainer = SFTTrainer(
    model=model,                 # your preloaded Qwen model
    train_dataset=dataset,       # from Cell 1
    peft_config=lora_config,
    args=sft_config,
    callbacks=[VerboseCallback()]  # attach callback instance (note parentheses)
)

print("🚀 Starting supervised fine-tuning...")
trainer.train()
print("✅ Training complete!")

# Save LoRA adapters after training
final_model_path = "./qwen_sft_final"
trainer.save_model(final_model_path)
print(f"✅ LoRA adapters saved to: {final_model_path}")

# Save the final fine-tuned model adapters.
final_model_path = "./qwen_sft_final"
trainer.save_model(final_model_path)
print(f"Final model saved to {final_model_path}")

# ================================
# == OPTIMIZATION SUMMARY ==
# No changes were needed. The beauty of LoRA is that you're only saving the "adapter" weights,
# which are tiny (a few megabytes) compared to the multi-gigabyte base model. This step is already
# very resource-friendly.
# ================================

from transformer_lens import HookedTransformer
import gc
import torch

print("\n" + "="*50)
print("🚀 Running the 'AFTER' benchmark on the fine-tuned model ...")
print("="*50)

# Use the same test_prompt and chat_prompt as before
chat_prompt = tokenizer.apply_chat_template(
    [
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": test_prompt},
    ],
    tokenize=False,
    add_generation_prompt=True,
)

# Generate with fine-tuned LoRA model
inputs = tokenizer(chat_prompt, return_tensors="pt").to(model.device)
generated_ids = model.generate(inputs.input_ids, do_sample=False)
finetuned_output_text = tokenizer.decode(generated_ids[0])

print("\n--- Fine-tuned Model Output ---\n")
print(finetuned_output_text)
print("\n------------------------------\n")

# Run HookedTransformer analysis on the fine-tuned output
hooked_model = HookedTransformer.from_pretrained(model_id)
hooked_model.to("cuda" if torch.cuda.is_available() else "cpu")
hooked_model.eval()

print("Analyzing the fine-tuned generation process...")
with torch.no_grad():
    _, finetuned_cache = hooked_model.run_with_cache(finetuned_output_text)

# Clean up memory
del hooked_model
del finetuned_cache
gc.collect()
torch.cuda.empty_cache()

print("✅ 'AFTER' benchmark complete.")

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
from transformer_lens import HookedTransformer
import gc

# ====== 1. Paths and Base Model ======
base_model_id = "Qwen/Qwen1.5-0.5B-Chat"   # Base model
peft_model_path = "./qwen_sft_final"       # Your fine-tuned adapter folder

# ====== 2. Load Tokenizer ======
print("📦 Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(base_model_id)

# ====== 3. Load Base Model in 4-bit & Apply LoRA Adapters ======
print("📦 Loading base model...")
model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    load_in_4bit=True,              # Can change to load_in_8bit=True if preferred
    device_map="auto"
)

print("📦 Loading LoRA adapters...")
model = PeftModel.from_pretrained(model, peft_model_path)
model.eval()

# ====== 4. Test Prompt ======
test_prompt = """
Write a Python program that shows 20 balls bouncing inside a spinning hexagon:
- All balls have the same radius.
- All balls have a number on it from 1 to 20.
- All balls drop from the heptagon center when starting.
- Colors are: #f8b862, #f6ad49, #f39800, #f08300, #ec6d51, #ee7948, #ed6d3d, #ec6800, #ec6800, #ee7800, #eb6238, #ea5506, #ea5506, #eb6101, #e49e61, #e45e32, #e17b34, #dd7a56, #db8449, #d66a35
- The balls should be affected by gravity and friction, and they must bounce off the rotating walls realistically. There should also be collisions between balls.
- The material of all the balls determines that their impact bounce height will not exceed the radius of the heptagon, but higher than ball radius.
- All balls rotate with friction, the numbers on the ball can be used to indicate the spin of the ball.
- The heptagon is spinning around its center, and the speed of spinning is 360 degrees per 5 seconds.
- The heptagon size should be large enough to contain all the balls.
- Do not use the pygame library; implement collision detection algorithms and collision response etc. by yourself. The following Python libraries are allowed: tkinter, math, numpy, dataclasses, typing, sys.
- All codes should be put in a single Python file.
"""

chat_prompt = tokenizer.apply_chat_template(
    [
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": test_prompt},
    ],
    tokenize=False,
    add_generation_prompt=True,
)

# ====== 5. Generate with Large max_new_tokens ======
print("\n🚀 Generating with fine-tuned model...")
inputs = tokenizer(chat_prompt, return_tensors="pt").to(model.device)
generated_ids = model.generate(
    inputs.input_ids,
    do_sample=True,          # Enable sampling for top_p to work
    top_p=0.9,
    temperature=0.7,
    max_new_tokens=10000,     # Increased to allow full code generation
    repetition_penalty=1.1
)
finetuned_output_text = tokenizer.decode(generated_ids[0], skip_special_tokens=False)

print("\n--- Fine-tuned Model Output ---\n")
print(finetuned_output_text)
print("\n------------------------------\n")

# ====== 6. HookedTransformer Analysis ======
print("📊 Loading HookedTransformer for analysis...")
hooked_model = HookedTransformer.from_pretrained(base_model_id)
hooked_model.to("cuda" if torch.cuda.is_available() else "cpu")
hooked_model.eval()

print("🔍 Analyzing the fine-tuned generation process...")
with torch.no_grad():
    _, finetuned_cache = hooked_model.run_with_cache(finetuned_output_text)

print("✅ 'AFTER' benchmark & analysis complete.")

# del hooked_model
# del finetuned_cache
del model
gc.collect()
torch.cuda.empty_cache()

!zip -r output_zip_file.zip qwen_sft_final/

!zip -r qwen_finetuned_sft.zip qwen-sft-finetuned/

from google.colab import files
        files.download('output_zip_file.zip')

from google.colab import files
        files.download('qwen_finetuned_sft.zip')

!unzip qwen_finetuned_sft.zip -d qwen_sft_final



# Cell 1 — Merge LoRA and save a standalone HF model

import os
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

base_model_id = "Qwen/Qwen1.5-0.5B-Chat"
peft_model_path = "./qwen_sft_final/qwen-sft-finetuned/checkpoint-250"  # your adapter checkpoint
merged_model_dir = "/content/qwen_merged"  # absolute path avoids confusion

# 1) Load base model + tokenizer
tokenizer = AutoTokenizer.from_pretrained(base_model_id)
base_model = AutoModelForCausalLM.from_pretrained(
    base_model_id,
    device_map="auto",
    torch_dtype=None  # let HF choose based on weights; fine for colab GPU
)

# 2) Load LoRA and merge into base
lora_model = PeftModel.from_pretrained(base_model, peft_model_path)
merged_model = lora_model.merge_and_unload()

# 3) Save merged model & tokenizer
os.makedirs(merged_model_dir, exist_ok=True)
merged_model.save_pretrained(merged_model_dir)
tokenizer.save_pretrained(merged_model_dir)

# 4) Verify save
print("✅ Merged model saved to:", merged_model_dir)
print("Contents:", os.listdir(merged_model_dir))
assert any(f in os.listdir(merged_model_dir) for f in ["pytorch_model.bin","model.safetensors"]), "No weight file found!"
assert "config.json" in os.listdir(merged_model_dir), "config.json missing!"

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import pandas as pd
from transformers import AutoModelForCausalLM, AutoTokenizer
import os

merged_model_dir = "/content/qwen_merged"

# Load merged model
tokenizer = AutoTokenizer.from_pretrained(merged_model_dir)
model = AutoModelForCausalLM.from_pretrained(
    merged_model_dir,
    device_map="auto",
    torch_dtype=None
)
model.eval()
device = next(model.parameters()).device

# Prompts: differ only in the called function name
clean_prompt = (
    "def add(a, b):\n"
    "    return a + b\n\n"
    "def main():\n"
    "    result = add(3, 4)\n"
    "    print(result)"
)
corrupt_prompt = (
    "def add(a, b):\n"
    "    return a + b\n\n"
    "def main():\n"
    "    result = subtract(3, 4)\n"
    "    print(result)"
)

def encode(s: str):
    return tokenizer(s, return_tensors="pt").to(device)

clean_inputs = encode(clean_prompt)
corrupt_inputs = encode(corrupt_prompt)

# ---- Metric: logit diff for single-token " add" vs " subtract"
def single_token_id(tok, s):
    ids = tok.encode(s, add_special_tokens=False)
    return ids[0] if len(ids) == 1 else None

add_id = single_token_id(tokenizer, " add") or single_token_id(tokenizer, "add")
sub_id = single_token_id(tokenizer, " subtract") or single_token_id(tokenizer, "subtract")
if add_id is None or sub_id is None:
    raise ValueError("Couldn't find single-token ids for 'add'/'subtract' with this tokenizer.")

@torch.no_grad()
def logits_only(inp):
    out = model(**inp, use_cache=False, return_dict=True)
    return out.logits

def logit_diff_from_logits(logits):
    # Compare at final position
    return (logits[0, -1, add_id] - logits[0, -1, sub_id]).float()

# Baseline score on clean input
clean_logits = logits_only(clean_inputs)
base_score = logit_diff_from_logits(clean_logits).item()
print("Baseline clean logit diff:", base_score)

# ---- Cache residual stream (pre- and post-block) for both prompts
# Qwen2 has layers at model.model.layers[i]; we hook the entire decoder layer
def run_with_cache(inputs):
    cache = {"resid_pre": {}, "resid_post": {}}
    hooks = []

    def make_pre_hook(i):
        def pre_hook(module, inputs):
            # inputs: (hidden_states, attention_mask, position_ids, ... )
            hs = inputs[0]
            cache["resid_pre"][i] = hs.detach().clone()
        return pre_hook

    def make_post_hook(i):
        def post_hook(module, inputs, output):
            # output is hidden_states after block
            cache["resid_post"][i] = output.detach().clone()
        return post_hook

    for i, layer in enumerate(model.model.layers):
        hooks.append(layer.register_forward_pre_hook(make_pre_hook(i)))
        hooks.append(layer.register_forward_hook(make_post_hook(i)))

    with torch.no_grad():
        _ = model(**inputs, use_cache=False, return_dict=True)

    for h in hooks: h.remove()
    return cache

clean_cache = run_with_cache(clean_inputs)
corrupt_cache = run_with_cache(corrupt_inputs)

# ---- Activation patching:
# For each (layer, position), replace clean resid_pre with corrupt resid_pre at that position, then re-run and measure metric.
seq_len = clean_inputs["input_ids"].shape[1]
n_layers = len(model.model.layers)
effect = torch.empty(n_layers, seq_len, device="cpu")

@torch.no_grad()
def run_with_patch_at(layer_idx: int, pos: int):
    h = None

    def pre_hook(module, inputs):
        hs = inputs[0]
        # clone to avoid in-place issues
        hs = hs.clone()
        hs[:, pos, :] = corrupt_cache["resid_pre"][layer_idx][:, pos, :]
        # return a full inputs tuple with modified hidden_states
        new_inputs = (hs,) + inputs[1:]
        return new_inputs

    h = model.model.layers[layer_idx].register_forward_pre_hook(pre_hook)
    out = model(**clean_inputs, use_cache=False, return_dict=True)
    h.remove()
    return out.logits

print("Patching across layers x positions...")
for i in range(n_layers):
    for p in range(seq_len):
        patched_logits = run_with_patch_at(i, p)
        score = logit_diff_from_logits(patched_logits).item()
        effect[i, p] = score - base_score  # delta vs baseline

# ---- Visualize
df = pd.DataFrame(
    effect.numpy(),
    index=[f"Layer {i}" for i in range(n_layers)],
    columns=[f"Pos {i}" for i in range(seq_len)]
)

plt.figure(figsize=(12, 8))
plt.title("Residual-pre Activation Patching (Δ logit: 'add' − 'subtract')")
plt.xlabel("Token Position")
plt.ylabel("Layer")
im = plt.imshow(df, aspect="auto", cmap="viridis")
plt.colorbar(im, label="Score change vs baseline")
plt.tight_layout()
plt.show()

# Optional: print tokenized prompt to map positions
decoded_tokens = [tokenizer.decode([tid]) for tid in clean_inputs["input_ids"][0].tolist()]
print("Token positions:", list(enumerate(decoded_tokens)))

torch.cuda.empty_cache()
import gc
gc.collect()


